#!/bin/sh
# -*- mode: sh -*-

TARGET_SESSION="$1"
if [ -z "$TARGET_SESSION" ]; then
    TARGET_SESSION="$(tmux display-message -p '#S')"
fi


# Window "editor"
tmux rename-window -t "$TARGET_SESSION":1 editor

tmux send-keys -t "$TARGET_SESSION":1.1 e C-m

tmux splitw -h -t "$TARGET_SESSION":1 -p 33
tmux send-keys -t "$TARGET_SESSION":1.2 guard C-m

tmux splitw -v -t "$TARGET_SESSION":1.2

tmux select-pane -t "$TARGET_SESSION":1.1


# Window "server"
tmux new-window -t "$TARGET_SESSION":2 -n server

tmux send-keys -t "$TARGET_SESSION":2.1 bundle\ exec\ rails\ s C-m

tmux splitw -t "$TARGET_SESSION":2
tmux send-keys -t "$TARGET_SESSION":2.2 tail\ -f\ log/development.log C-m

tmux select-layout -t "$TARGET_SESSION":2 even-horizontal

tmux select-pane -t "$TARGET_SESSION":2.1


#  Select
tmux select-window -t "$TARGET_SESSION":1
tmux select-pane -t "$TARGET_SESSION":1.1
