#!/bin/sh
# -*- mode: sh -*-

############################################
# local
############################################

LOCAL_DIR="$HOME/local"
LOCAL_OS_DIR="$LOCAL_DIR/${ESH_OS}"
LOCAL_OS_ARCH_DIR="$LOCAL_OS_DIR/${ESH_OS_ARCH}"
export LOCAL_DIR LOCAL_OS_DIR LOCAL_OS_ARCH_DIR

if [ -n "$HOME_ALT" ]; then
    LOCAL_ALT_DIR="$HOME_ALT/local"
    LOCAL_ALT_OS_DIR="$LOCAL_ALT_DIR/${ESH_OS}"
    LOCAL_ALT_OS_ARCH_DIR="$LOCAL_ALT_OS_DIR/${ESH_OS_ARCH}"

    export LOCAL_ALT_DIR LOCAL_ALT_OS_DIR LOCAL_ALT_OS_ARCH_DIR
fi

path_load_local()
{
    path_addin_pre "$LOCAL_OS_ARCH_DIR"
    path_addin_pre "$LOCAL_OS_DIR"
    path_addin_pre "$LOCAL_DIR"
    path_addin_pre "$LOCAL_ALT_OS_ARCH_DIR"
    path_addin_pre "$LOCAL_ALT_OS_DIR"
    path_addin_pre "$LOCAL_ALT_DIR"
}
path_load_local

path_reload_local()
{
    path_purge "$LOCAL_DIR"
    path_purge "$LOCAL_ALT_DIR"
    path_load_local
}

#

local_pkgconfig_path_list()
{
    for local_pkgconfig_path_list__d in "$LOCAL_OS_ARCH_DIR" "$LOCAL_OS_DIR" "$LOCAL_DIR" "$LOCAL_ALT_OS_ARCH_DIR" "$LOCAL_ALT_OS_DIR" "$LOCAL_ALT_DIR"; do
        [ -z "$local_pkgconfig_path_list__d" ] && continue
        for local_pkgconfig_path_list__d_in in "$local_pkgconfig_path_list__d"/*/; do
            local_pkgconfig_path_list__d_in="${local_pkgconfig_path_list__d_in%/}"
            local_pkgconfig_path_list__d_in_short="${local_pkgconfig_path_list__d_in##*/}"

            case $local_pkgconfig_path_list__d_in_short in
                _*) continue ;;
            esac

            [ -d "${local_pkgconfig_path_list__d_in}/lib/pkgconfig" ] || continue
            echo "$local_pkgconfig_path_list__d_in"
        done
    done
}

local_pkgconfig_path_add()
{
    for local_pkgconfig_path_add__p; do
        [ -z "$local_pkgconfig_path_add__p" ] && continue
        local_pkgconfig_path_add__p="${local_pkgconfig_path_add__p%/}"

        case $local_pkgconfig_path_add__p in
            */pkgconfig) ;;
            */lib) local_pkgconfig_path_add__p="${local_pkgconfig_path_add__p}/pkgconfig" ;;
            *) local_pkgconfig_path_add__p="${local_pkgconfig_path_add__p}/lib/pkgconfig" ;;
        esac

        pkgconfig_path_add "$local_pkgconfig_path_add__p"
    done
}

local_pkgconfig_path()
{
    if [ $# -eq 0 ]; then
        local_pkgconfig_path_list
    else
        local_pkgconfig_path_add "$@"
    fi
}


############################################
