#!/bin/sh
# -*- mode: sh -*-


load_flatpak_path()
{
    for d in "$HOME_ALT/.local/share/flatpak" \
             "$HOME/.local/share/flatpak" \
             "/var/lib/flatpak"
    do
        if [ -d "$d" ]; then
            path_add_pre_post "${d}/exports/bin"
        fi
    done
}

load_flatpak_path
