#!/bin/sh
# -*- mode: sh -*-


### python
prompt_python()
{
    prompt_python=
    prompt_python__venv=
    prompt_python__ver=
    prompt_python__sep="${3:-:}"
    if [ -n "$VIRTUAL_ENV" ]; then
        prompt_python_venv="${VIRTUAL_ENV##*/}"
        if [ -n "$PROMPT_PYTHON_EXTENDED" ]; then
            prompt_python__ver=`python --version 2>/dev/null`
            prompt_python__ver="${prompt_python__ver#Python }"
        fi
        if [ "$prompt_python_venv" != 'default' ]; then
             prompt_python="${1}py${prompt_python__sep}${prompt_python_venv}${prompt_python__ver:+$prompt_python__sep$prompt_python__ver}${2}"
        fi
    fi
}

prompt_python_printf()
{
    if prompt_python; then
        [ -z "$prompt_python" ] || printf "${1:-%s}" "$prompt_python"
    fi
}


### ruby
prompt_ruby()
{
    prompt_ruby=

    prompt_rbenv "$@"
    prompt_ruby="$prompt_rbenv"
}

prompt_rbenv()
{
    prompt_rbenv=
    prompt_rbenv__sep="${3:-:}"
    if [ -n "$RBENV_VERSION" ]; then
        prompt_rbenv="rb:$RBENV_VERSION"
    else
        prompt_rbenv__version="`rbenv local 2>/dev/null`"
        [ $? -eq 0 ] || return 1
        if [ -n "$prompt_rbenv__version" ]; then
            prompt_rbenv="${1}rb${prompt_rbenv__sep}${prompt_rbenv__version}${2}"
        fi
    fi
}

prompt_ruby_printf()
{
    if prompt_ruby; then
        [ -z "$prompt_ruby" ] || printf "${1:-%s}" "$prompt_ruby"
    fi
}


### git
prompt_git()
{
    prompt_git=
    prompt_git_alt=
    if __git_prompt "$@"; then
        prompt_git="$__git_prompt"
        prompt_git_alt="$__git_prompt_alt"
    fi
}

prompt_git_printf()
{
    if prompt_git; then
        [ -z "$prompt_git" ] || printf "$1" "$prompt_git"
    fi
}
