#!/bin/sh
# -*- mode: sh -*-


########### tmux

if [ -f "$ESH_MODULE_DIR/bin/atmux" ]; then
    set --
    . "$ESH_MODULE_DIR/bin/atmux"

    export PATH="$PATH:$ESH_MODULE_DIR/bin"
fi


########### tmuxinator

export TMUXINATOR_CONFIG="$HOME/.tmuxinator"
