#!/bin/sh
# -*- mode: sh -*-


########### tmux

_want_auto_tmux()
{
    [ -r "$ESH_CONF_DIR/auto_tmux" ] || return 1

    if grep "^${HOSTNAME}$" "$ESH_CONF_DIR/auto_tmux" >/dev/null 2>&1 || grep "^${SHORT_HOSTNAME}$" "$ESH_CONF_DIR/auto_tmux" >/dev/null 2>&1; then
        return 0
    fi
    return 1
}

_has_tmux()
{
    which tmux >/dev/null 2>/dev/null
}

_inside_tmux()
{
    [ -n "$TMUX" ]
}

_not_inside_tmux()
{
    ! _inside_tmux
}

_ensure_tmux_is_running()
{
    _has_tmux || return 0

    if _not_inside_tmux; then
        _atmux
    fi
}

_tmux_session_exists()
{
    [ -z "$1" ] && return 1
    tmux has-session -t "$1"
}

_tmux_session_name_for()
{
    _tmux_session_name_for__base="$1"
    if [ -z "$_tmux_session_name_for__base" ]; then
        if [ "$PWD" = "$HOME" ]; then
            _tmux_session_name_for__base="home"
        else
            _tmux_session_name_for__base="${PWD##*/}"
        fi
    fi
    _tmux_session_name_for="$(echo $_tmux_session_name_for__base | tr :. _)"
}

_atmux()
{
    _has_tmux || return 1

    _tmux_session_name_for "$1"
    _atmux__session_name="$_tmux_session_name_for"

    tmux has-session -t "$_atmux__session_name" ||
        tmux new-session -d -s "$_atmux__session_name" ||
        return 1
    if _not_inside_tmux; then
        tmux attach -t "$_atmux__session_name"
    else
        tmux switch-client -t "$_atmux__session_name"
    fi
}


########### tmuxinator

export TMUXINATOR_CONFIG="$HOME/.tmuxinator"
