#!/bin/sh
# -*- mode: sh -*-


TARGET_SESSION="$1"
if [ -z "$TARGET_SESSION" ]; then
    tty=$(tty)
    TARGET_SESSION=$(
        for s in $(tmux list-sessions -F '#{session_name}'); do
            tmux list-panes -F '#{pane_tty} #{session_name}' -t "$s"
        done | grep "^$tty " | awk '{print $2}'
                        )
fi
if [ -z "$TARGET_SESSION" ]; then
    echo >&2 "cannot define target session"
    exit 1
fi


#

# Window "main"
tmux rename-window -t "$TARGET_SESSION":1 main

tmux send-keys -t "$TARGET_SESSION":1.1 e C-m

tmux splitw -h -t "$TARGET_SESSION":1 -p 33
tmux send-keys -t "$TARGET_SESSION":1.2 rgr C-m

tmux splitw -v -t "$TARGET_SESSION":1.2

tmux select-pane -t "$TARGET_SESSION":1.1


# Window "server"
tmux new-window -t "$TARGET_SESSION":2 -n server

tmux send-keys -t "$TARGET_SESSION":2.1 run server C-m

tmux splitw -t "$TARGET_SESSION":2
tmux send-keys -t "$TARGET_SESSION":2.2 tail\ -f\ log/....log C-m

tmux select-layout -t "$TARGET_SESSION":2 even-horizontal

tmux select-pane -t "$TARGET_SESSION":2.1


#  Select
tmux select-window -t "$TARGET_SESSION":1
tmux select-pane -t "$TARGET_SESSION":1.1
