#!/bin/sh
# -*- mode: sh -*-


tmux_context()
{
    tmux_context__session="$1"

    if [ -z "$tmux_context__session" ]; then
        tty=$(tty)
        tmux_context__session=$(
            for s in $(tmux list-sessions -F '#{session_name}'); do
                tmux list-panes -F '#{pane_tty} #{session_name}' -t "$s"
            done | grep "^$tty " | awk '{print $2}'
                             )
    fi

    tmux_context__window=$(tmux list-panes -F '#{active_window_index}' -t "$tmux_context__session")
}

tmux_context "$1"
TARGET_SESSION="${1:-$tmux_context__session}"
TARGET_WINDOW="${2:-$tmux_context__window}"

if [ -z "$TARGET_SESSION" ]; then
    echo >&2 "cannot define target session"
    exit 1
fi


#


# dev
tmux send-keys -t "$TARGET_SESSION":"$TARGET_WINDOW".1 e C-m

tmux splitw -h -t "$TARGET_SESSION":"$TARGET_WINDOW" -p 33
tmux send-keys -t "$TARGET_SESSION":"$TARGET_WINDOW".2 rgr C-m

tmux splitw -v -t "$TARGET_SESSION":"$TARGET_WINDOW".2 -p66

tmux select-pane -t "$TARGET_SESSION":"$TARGET_WINDOW".1


#  Select
tmux select-window -t "$TARGET_SESSION":"$TARGET_WINDOW"
tmux select-pane -t "$TARGET_SESSION":"$TARGET_WINDOW".1
