#!/bin/sh


###################
# ##### SET ##### #
###################



######################
# ##### SETOPT ##### #
######################

# List default zsh options
# emulate -lLR zsh
# Revert to default zsh options
# emulate -LR zsh

## Shell Emulation
setopt   shwordsplit
## Expansion and Globbing
setopt   globsubst
setopt   nonomatch
## Input/Output
setopt   rmstarsilent

## History
# share history across multiple zsh sessions
# setopt SHARE_HISTORY
# append to history
setopt APPEND_HISTORY
# adds commands as they are typed, not at shell exit
setopt INC_APPEND_HISTORY
# expire duplicates first
setopt HIST_EXPIRE_DUPS_FIRST
# do not store duplications
setopt HIST_IGNORE_DUPS
# setopt  HIST_IGNORE_ALL_DUPS
# ignore duplicates when searching
setopt HIST_FIND_NO_DUPS
# removes blank lines from history
setopt HIST_REDUCE_BLANKS
# verify history replacement
setopt HIST_VERIFY
# do not save duplications
setopt HIST_SAVE_NO_DUPS

## Correction
setopt CORRECT
setopt CORRECT_ALL


# non interactive
#
#
#setopt   allexport            # assumes all variable assignments are exported to the environment
#setopt   extendedglob         # enable extended globbing.
#
# interactive
#
#setopt   INTERACTIVE_COMMENTS # Allow comments even in interactive shells.
#
#unsetopt hist_beep            # no beep
#setopt   interactivecomments  # allows comments in the interactive shell. Useful for pasting.
#unsetopt list_beep            # no beep
#setopt   promptsubst          # parameter, command, and arithmetic substitution are performed in prompts.
#setopt   pushdignoredups      # ignores directory stack duplicates.
#unsetopt rm_star_silent       # prompt for rm *


####


#unsetopt clobber		# >| to overwrite file
#unsetopt ignore_eof		# CTRL + D => logout
#setopt	print_exit_value	# affiche l'exitcode si != 0

##setopt	 nullglob		# remove glob no output errors
##setopt   menu_complete		# completion schema B
#unsetopt list_ambiguous		# completion schema C
#setopt	 auto_remove_slash	# remove completion end slash when press space
##unsetopt glob_dots		# no completion on dot files
#setopt   chase_links		# sym links management
#setopt	 hist_verify		# check command beginning with ! (history)
#unsetopt hup			# no HUP send to process when closing shell
#unsetopt bg_nice		# bg jobs niced to 0


#setopt   notify
#setopt   globdots
#setopt   cdablevars
#setopt   autolist

#setopt   recexact
#setopt   longlistjobs
#setopt   autoresume
#setopt   histignoredups

#setopt   extendedglob
#setopt   rcquotes
#setopt   mailwarning
#unsetopt autoparamslash
