#!/bin/sh

[ $# -lt 1 ] && exit 1

cmd="$1"
shift

real_cmd="$(which $cmd)" || {
    echo >&2 "could not resolve \"$cmd\""
    exit 1
}

file "$real_cmd" | grep -q 'shell script' || {
    echo >&2 "\"$cmd\" resolving as \"$real_cmd\" is not a shell script"
    exit 2
}

sh -x "$(which $cmd)" "$@"
